name: Distribuir proyecto

on:
  push:
    tags:
      - 'debug*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar ANT
        uses: cedx/setup-ant@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Añadir Logisim-Evolution como librería
        run: |
          mkdir plugins/lib && cd plugins/lib
          wget "https://github.com/logisim-evolution/logisim-evolution/releases/download/v3.9.0/logisim-evolution-3.9.0-all.jar"
          wget "https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.17.0/byte-buddy-1.17.0.jar"
          wget "https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.17.0/byte-buddy-agent-1.17.0.jar"
          wget "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"
          wget "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar"
          wget "https://repo1.maven.org/maven2/org/mockito/mockito-core/5.20.0/mockito-core-5.20.0.jar"
          wget "https://repo1.maven.org/maven2/org/objenesis/objenesis/3.3/objenesis-3.3.jar"

      - name: Ejecutar ANT
        run: cd plugins && ant jar

      - name: Configurar M32 en perfil "Release"
        run: python release.py

      - name: Configurar directorios
        run: |
          mkdir lib
          cp plugins/dist/M32Library.jar lib/M32Library.jar
          cp plugins/lib/logisim-evolution-3.9.0-all.jar logisim-evolution.jar
          cp tools/src/ensamblador/ensamblador.py tools/ensamblador.py
          cp tools/src/microensamblador/microensamblador.py tools/microensamblador.py
          cp tools/printf.s tools/examples/printf.s
      
      - name: Compresión de archivos
        run: zip release.zip -@ < package.txt

      - name: Crear release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
