name: Distribuir proyecto

on:
  push:
    branches: [ master ]
    tags:
      - 'debug*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar ANT
        uses: cedx/setup-ant@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Añadir Logisim-Evolution como librería
        run: |
          mkdir plugins/lib && cd plugins/lib
          wget "https://github.com/logisim-evolution/logisim-evolution/releases/download/v3.9.0/logisim-evolution-3.9.0-all.jar"

      - name: Ejecutar ANT
        run: cd plugins && ant jar

      - name: Configurar M32 en perfil "Release"
        run: python release.py

      - name: Configurar directorios
        run: |
          mkdir lib
          cp plugins/dist/M32Library.jar lib/M32Library.jar
          cp plugins/lib/logisim-evolution-3.9.0-all.jar logisim-evolution.jar

      - name: Crear release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lib/M32Library.jar
            logisim-evolution.jar
            M32 Release.circ
            run.bat
            run.sh
